const FETCH_ARTISTS_LIST = 'FETCH_ARTISTS_LIST';
const FETCH_ARTISTS_LIST_SUCCESS = 'FETCH_ARTISTS_LIST_SUCCESS';
const FETCH_ARTISTS_LIST_FAILURE = 'FETCH_ARTISTS_LIST_FAILURE';

const FETCH_ARTIST_INFO = 'FETCH_ARTIST_INFO';
const FETCH_ARTIST_INFO_FAILURE = 'FETCH_ARTIST_INFO_FAIL';
const FETCH_ARTIST_INFO_SUCCESS = 'FETCH_ARTIST_INFO_SUCCESS';

export {
  FETCH_ARTISTS_LIST,
  FETCH_ARTISTS_LIST_SUCCESS,
  FETCH_ARTISTS_LIST_FAILURE,

  FETCH_ARTIST_INFO,
  FETCH_ARTIST_INFO_FAILURE,
  FETCH_ARTIST_INFO_SUCCESS
};