const FETCH_ARTISTS_LIST = 'FETCH_ARTISTS_LIST';
const FETCH_ARTISTS_LIST_SUCCESS = 'FETCH_ARTISTS_LIST_SUCCESS';
const FETCH_ARTISTS_LIST_FAILURE = 'FETCH_ARTISTS_LIST_FAILURE';

const FETCH_ARTIST_INFO = 'FETCH_ARTIST_INFO';
const FETCH_ARTIST_INFO_FAILURE = 'FETCH_ARTIST_INFO_FAIL';
const FETCH_ARTIST_INFO_SUCCESS = 'FETCH_ARTIST_INFO_SUCCESS';

const FETCH_ALBUM_INFO = 'FETCH_ALBUM_INFO';
const FETCH_ALBUM_INFO_SUCCESS = 'FETCH_ALBUM_INFO_SUCCESS';
const FETCH_ALBUM_INFO_FAILURE = 'FETCH_ALBUM_INFO_FAILURE';

const FETCH_TOP_ALBUMS = 'FETCH_TOP_ALBUMS';
const FETCH_TOP_ALBUMS_SUCCESS = 'FETCH_TOP_ALBUMS_SUCCESS';
const FETCH_TOP_ALBUMS_FAILURE = 'FETCH_TOP_ALBUMS_FAILURE';

const LOGOUT = 'LOGOUT';

const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
const CURRENT_USER_FETCHED = 'CURRENT_USER_FETCHED';

const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST';
const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';
const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';

export {
  FETCH_ARTISTS_LIST,
  FETCH_ARTISTS_LIST_SUCCESS,
  FETCH_ARTISTS_LIST_FAILURE,
  FETCH_ARTIST_INFO,
  FETCH_ARTIST_INFO_FAILURE,
  FETCH_ARTIST_INFO_SUCCESS,
  FETCH_ALBUM_INFO,
  FETCH_ALBUM_INFO_FAILURE,
  FETCH_ALBUM_INFO_SUCCESS,
  FETCH_TOP_ALBUMS,
  FETCH_TOP_ALBUMS_SUCCESS,
  FETCH_TOP_ALBUMS_FAILURE,
  LOGOUT,
  FETCH_CURRENT_USER,
  CURRENT_USER_FETCHED,
  GET_REVIEWS_FAILURE,
  GET_REVIEWS_REQUEST,
  GET_REVIEWS_SUCCESS,
  POST_REVIEW_FAILURE,
  POST_REVIEW_REQUEST,
  POST_REVIEW_SUCCESS
};